name: Push ghcr.io mitmproxy image
on:
  # rebuild and push the container, updating dependencies, every 6 hours
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches: [master]
    paths:
    - 'proxies/mitmproxy'

permissions:
  packages: write

jobs:
  mitmproxy-image:
    timeout-minutes: 10
    name: Build and push mitmproxy to GHCR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push to GHCR
      uses: docker/build-push-action@v6
      with:
        context: ./proxies/mitmproxy
        push: true
        tags: |
          ghcr.io/lappihuan/kubetap-mitmproxy:latest
          ghcr.io/lappihuan/kubetap-mitmproxy:${{ github.sha }}
